/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backuptool.gui;

import backuptool.classes.FolderCopy;
import java.awt.Color;
import javax.swing.JFileChooser;

/**
 *
 * @author Usuario
 */
public class FrMain extends javax.swing.JFrame {

    /**
     * Creates new form FrMain
     */
    public FrMain() {
        initComponents();
        fcObj = new FolderCopy();
        BtnCopyDir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnDirOrigin = new javax.swing.JButton();
        BtnDirDest = new javax.swing.JButton();
        LblFolderOrig = new javax.swing.JLabel();
        LblFolderDest = new javax.swing.JLabel();
        BtnClose = new javax.swing.JButton();
        BtnCopyDir = new javax.swing.JButton();
        LblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BackupTools v1.0");

        BtnDirOrigin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnDirOrigin.setText("Selecionar Pasta Origem");
        BtnDirOrigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDirOriginActionPerformed(evt);
            }
        });

        BtnDirDest.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnDirDest.setText("Selecionar Pasta Destino");
        BtnDirDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDirDestActionPerformed(evt);
            }
        });

        LblFolderOrig.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        LblFolderDest.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        BtnClose.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnClose.setText("Fechar");
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });

        BtnCopyDir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnCopyDir.setText("Copiar");
        BtnCopyDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCopyDirActionPerformed(evt);
            }
        });

        LblStatus.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BtnDirOrigin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnDirDest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(LblFolderOrig, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BtnCopyDir, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(LblFolderDest, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(LblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BtnDirOrigin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblFolderOrig, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnDirDest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblFolderDest, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCopyDir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDirOriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDirOriginActionPerformed
        // TODO add your handling code here:
        LblStatus.setText("");       
        BtnCopyDir.setEnabled(false);
        LblFolderDest.setText("");
        jfOrig = new JFileChooser();
        jfOrig.setCurrentDirectory(new java.io.File("."));
        jfOrig.setDialogTitle("Selecione a pasta de origem");
        jfOrig.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfOrig.setAcceptAllFileFilterUsed(false);
        jfOrig.showOpenDialog(null);
        LblFolderOrig.setText(jfOrig.getSelectedFile().toString());
    }//GEN-LAST:event_BtnDirOriginActionPerformed

    private void BtnDirDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDirDestActionPerformed
        // TODO add your handling code here:
        jfDest = new JFileChooser();
        jfDest.setCurrentDirectory(new java.io.File("."));
        jfDest.setDialogTitle("Selecione a pasta de destino");
        jfDest.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfDest.setAcceptAllFileFilterUsed(false);
        jfDest.showOpenDialog(null);
        LblFolderDest.setText(jfDest.getSelectedFile().toString());
        if ((!LblFolderOrig.getText().equals("")) && (!LblFolderDest.getText().equals(""))) {
            BtnCopyDir.setEnabled(true);
        } else {
            BtnCopyDir.setEnabled(false);
        }
            
    }//GEN-LAST:event_BtnDirDestActionPerformed

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BtnCloseActionPerformed

    private void BtnCopyDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCopyDirActionPerformed
        // TODO add your handling code here:       
        LblStatus.setText("Copiando arquivos...");
        fcObj.setFolderOrigin(jfOrig.getSelectedFile().toString());
        fcObj.setFolderDest(jfDest.getSelectedFile().toString());        
        if (fcObj.CopyDirectory()) {
            LblStatus.setForeground(Color.GREEN);
            LblStatus.setText("Processo finalizado !");
        } 
        else 
        {
            LblStatus.setForeground(Color.red);
            LblStatus.setText("Falha ao copiar os arquivos !");
        }
    }//GEN-LAST:event_BtnCopyDirActionPerformed

    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {*/
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     /*   try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
   /*     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMain().setVisible(true);
            }
        });
    }*/

    FolderCopy fcObj;
    JFileChooser jfDest;
    JFileChooser jfOrig;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClose;
    private javax.swing.JButton BtnCopyDir;
    private javax.swing.JButton BtnDirDest;
    private javax.swing.JButton BtnDirOrigin;
    private javax.swing.JLabel LblFolderDest;
    private javax.swing.JLabel LblFolderOrig;
    private javax.swing.JLabel LblStatus;
    // End of variables declaration//GEN-END:variables
}
